### ISSUE TITLE
Service sinope.set_outside_temperature

### ISSUE THREAD

**Issue by simtreti** [claudegel/sinope-gt125#39]
Bonjour,

Le service sinope.set_outside_temperature ne semble pas fonctionner, quand j'essaie de caller le service manuellement par les developper tools avec la variable temperature comme ceci: temperature: "{{ state_attr('weather.home', 'temperature') }}" j'obtient ce code d'erreur. Failed to call service sinope/set_outside_temperature. expected float for dictionary value @ data['temperature']

Pouvez vous m'aider, en fait je voudrais être en mesure de pousser la valeur de temperature de ma sonde exterieur dans l'affichage secondaire du thermostat à l'aide d'une automation toute les 5 minutes.

**Comment by claudegel** [comment]
Désolé je n'avais pas vu ce message

voici coment je fais pour envoyer la température au thermostat à toutes les 59 minutes. Si on dépasse ce délais le thermostat retourne à l'affichage de base. Tu peux réduire le délais si besoin:
```
#################################
###       envoyer temperature extérieur aux thermostats
#################################
  - id: hourly outside temp
    alias: Envoyer temperature exterieure au thermostat
    initial_state: true
    trigger:
      platform: time_pattern
      minutes: "/59"
    action:
      - service: sinope.set_outside_temperature
        data_template:
          entity_id: climate.sinope_climate_bureau
          temperature: "{{ state_attr('weather.openweathermap', 'temperature') }}"
```
si tu as ton propre sensor extérieur c'est encore mieux. Tu dois valider que la température de ton sensor est en format decimal et non texte. Ton erreur signale que le template attends un float qui est un chiffre avec décimal et il reçois probablement autre chose comme un format text.
Tu peux te créer un sensor comme ceci:
```
- platform: template
    sensors:
      temp_ext:
        friendly_name: "Température extérieure"
        value_template: "{{ state_attr('weather.home', 'Temperature') | float }}"
```

**Comment by simtreti** [comment]
Merci Claude, Voici ou je suis rendu.

j'ai créer un Sensor avec un template que voici.

sensor:
- platform: template
  sensors:
    temp_ext_float:
        friendly_name: "temp_ext_float"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.tasmota_ds18b20_temperature') | float }}"

J'ai belle et bien la valeur de la temperature exterieur dans cette entité.

Cependant quand je call le service sinope.set_outside_temperature comme ceci avec les developper tool

entity_id: climate.sinope_salon
temperature: "{{ states('sensor.temp_ext_float') }}"

J'ai encore ce message 
Failed to call service sinope/set_outside_temperature. expected float for dictionary value @ data['temperature']

Peux-etre il ya quelque chose que je comprends mal.

**Comment by claudegel** [comment]
Il y a souvent un auto convertion dans HA. Par exemple j'ai un sensor qui me donne la température de mon spa en oF j'ai tout essayé pour l'afficher en oF mais HA le converti toujours en oC.

Est-ce que to sensor tasmota transfert l'information via MQTT si oui, c'est en format text

rajoute | float dans ton setup

```
entity_id: climate.sinope_salon
temperature: "{{ states('sensor.temp_ext_float') |float }}"
```
J'ai testé de mon coté avec l'outil de développement et ca fonctionne pour envoyer la température en y mettant directement un chiffre
![service](https://user-images.githubusercontent.com/4268938/112772864-35fbe600-9001-11eb-931c-7ee235f3d4d0.png)
je vais tester en transférant le data d'un de mais 18b20

**Comment by simtreti** [comment]
Je crois que mon problème est que même manuellement quand j'inscrit un chiffre cela ne fonctionne pas. Par contre lorsque j'inscrit un chiffre sans decimal EX: temperature: 28 j'obtient le message d'erreur suivant: Failed to call service sinope/set_outside_temperature. non-hexadecimal number found in fromhex() arg at position 35

![image](https://user-images.githubusercontent.com/79706737/112773174-fdf5a280-9002-11eb-9701-6eb5e67c4944.png)

**Comment by claudegel** [comment]
Regarde l'example que je t'ai envoyé. j'ai juste 28 sans décimale et ca fonctionne.
par contre je vois que tu es avec une vieille version de HA car maintenant c'est 
service
Sinope GT125: set_outside_temperature

Quel versio de HA tu as et pour sinope-GT125 as tu la dernière version?

Ca ne marche pas via un template je vais fouiller ça

**Comment by simtreti** [comment]
J'ai pas la dernier version de HA, je vais me mettre à jour.
![image](https://user-images.githubusercontent.com/79706737/112773612-9a6c7480-9004-11eb-8870-6e03c73f8233.png)

Pour le Custom Component GT-125 j'ai la dernière version 1.5.1

**Comment by claudegel** [comment]
Ceci fonctionne
```
service: sinope.set_outside_temperature
data:
  entity_id: climate.sinope_climate_bureau
  temperature: 26.5
```
Par contre je vois que le nom de ton thermostat est pas comme le mien.
moi c'est: climate.sinope_climate_bureau
Si j'enl'eve le deuxieme climate dans le nom ca donne plein d'erreurs etranges

toi tu as juste climate.sinope_salon
to nom de entite est tu correcte ?
Dans ton log d'erreur ca mentionne une erreur au niveau de l'entity_id

**Comment by claudegel** [comment]
dans mon automation avec 
```
.....
action:
      - service: sinope.set_outside_temperature
        data_template:
          entity_id: climate.sinope_climate_bureau
          temperature: '{{ states.sensor.eau_spa |float }}'
```

Je n'ai pas d'erreur dans les logs mais ca semple pas fonctionner pour afficher sur le thermostat
